# Generated by Django 2.2.5 on 2019-09-25 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listdb',
            name='image',
            field=models.ImageField(default='', upload_to='list/image'),
        ),
    ]
