# Generated by Django 2.2.5 on 2019-09-26 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_login_detail'),
    ]

    operations = [
        migrations.CreateModel(
            name='registeringo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=8)),
            ],
        ),
        migrations.DeleteModel(
            name='listdb',
        ),
        migrations.DeleteModel(
            name='login_detail',
        ),
    ]
