# Generated by Django 2.2.5 on 2019-09-27 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20190926_1944'),
    ]

    operations = [
        migrations.CreateModel(
            name='service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('service', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'service',
            },
        ),
        migrations.AlterField(
            model_name='registeringo',
            name='username',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterModelTable(
            name='registeringo',
            table='registeringo',
        ),
    ]
