# Generated by Django 2.2.5 on 2019-09-27 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_auto_20190927_1052'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='service',
            new_name='log',
        ),
        migrations.AlterModelTable(
            name='log',
            table='log',
        ),
    ]
