# Generated by Django 2.2.5 on 2019-09-27 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_auto_20190927_1102'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='log',
            new_name='logtable',
        ),
        migrations.AlterModelTable(
            name='logtable',
            table='logtable',
        ),
    ]
