# Generated by Django 2.2.5 on 2019-09-27 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_auto_20190927_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='logtable',
            name='des',
            field=models.TextField(default='no', max_length=50),
            preserve_default=False,
        ),
    ]
