# Generated by Django 2.2.5 on 2019-09-27 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_auto_20190927_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='logtable',
            name='brand',
            field=models.CharField(default=' ', max_length=20),
            preserve_default=False,
        ),
    ]
