# Generated by Django 2.2.5 on 2019-09-27 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_logtable_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='logtable',
            name='email',
            field=models.CharField(default=' ', max_length=20),
            preserve_default=False,
        ),
    ]
