# Generated by Django 2.2.5 on 2019-09-27 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_logtable_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logtable',
            name='email',
            field=models.EmailField(max_length=20),
        ),
    ]
