# Generated by Django 2.2.5 on 2019-09-28 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0017_auto_20190928_0432'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logtable',
            old_name='opt',
            new_name='otp',
        ),
    ]
