# Generated by Django 2.2.5 on 2019-09-28 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0018_auto_20190928_0742'),
    ]

    operations = [
        migrations.AddField(
            model_name='logtable',
            name='status',
            field=models.TextField(default='pending'),
        ),
    ]
