# Generated by Django 2.2.5 on 2019-09-28 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0019_logtable_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='proregisteringo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=8)),
                ('email', models.TextField(max_length=8)),
                ('address', models.TextField(max_length=8)),
                ('phone', models.TextField(max_length=10)),
            ],
            options={
                'db_table': 'proregisteringo',
            },
        ),
    ]
