# Generated by Django 2.2.5 on 2019-09-28 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0020_proregisteringo'),
    ]

    operations = [
        migrations.AddField(
            model_name='proregisteringo',
            name='service',
            field=models.TextField(default='mobile', max_length=10),
            preserve_default=False,
        ),
    ]
