# Generated by Django 2.2.5 on 2019-09-28 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0022_auto_20190928_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logtable',
            name='address',
            field=models.TextField(max_length=80),
        ),
    ]
