# Generated by Django 2.2.5 on 2019-09-28 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0024_auto_20190928_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='logtable',
            name='servicep',
            field=models.TextField(default='ravi', max_length=20),
            preserve_default=False,
        ),
    ]
