# Generated by Django 2.2.5 on 2019-09-28 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0025_logtable_servicep'),
    ]

    operations = [
        migrations.CreateModel(
            name='feedadd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicep', models.CharField(max_length=10)),
                ('feed', models.TextField(max_length=20)),
            ],
            options={
                'db_table': 'feedadd',
            },
        ),
    ]
